#!/usr/bin/env bash
#
# common <tab> completions

# Brew completion
[[ -r “$(brew —-prefix)/etc/profile.d/bash_completion.sh” ]] && source “$(brew —-prefix)/etc/profile.d/bash_completion.sh”

# Enable bash <tab> completion for z
source "$(brew --prefix)/etc/profile.d/z.sh"

# SSH auto-completion based on entries in known_hosts.
if [[ -e "$HOME/.ssh/known_hosts" ]]; then
	complete -o default -W "$(cat "$HOME/.ssh/known_hosts" | sed 's/[, ].*//' | sort | uniq | grep -v '[0-9]')" ssh scp sftp
fi
