#!/usr/bin/env bash
#
# common <tab> completions

# Brew completion
[[ -r "/home/linuxbrew/.linuxbrew/etc/profile.d/bash_completion.sh" ]] && source "/home/linuxbrew/.linuxbrew/etc/profile.d/bash_completion.sh"

# Enable bash <tab> completion for Digital Ocean control panel
if brew list "doctl" &> /dev/null; then
	source <(doctl completion bash)
fi

# Enable bash <tab> completion for z
if brew list "z" &> /dev/null; then
	source "$(brew --prefix)/etc/profile.d/z.sh"
fi

# SSH auto-completion based on entries in known_hosts.
if [[ -e "$HOME/.ssh/known_hosts" ]]; then
	complete -o default -W "$(cat "$HOME/.ssh/known_hosts" | sed 's/[, ].*//' | sort | uniq | grep -v '[0-9]')" ssh scp sftp
fi
