#!/usr/bin/env bash

# Spare the hassle of typing cd every time;type the name of your target and
# Bash will understand
shopt -s autocd

# In bash, aliases are not expanded in shell scripts. This is not standardized
# among the POSIX-type shells. If you want aliases to be expanded in shell
# scripts, the shell script must use a bash-specific shell option
# https://github.com/sindresorhus/guides/blob/master/how-not-to-rm-yourself.md#safeguard-rm
shopt -s expand_aliases

# Autocorrect typos in path names when using `cd`
shopt -s cdspell
shopt -s dirspell

# Check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize

# Append to the Bash history file, rather than overwriting it
shopt -s histappend
# Allow use to re-edit a failed history substitution.
shopt -s histreedit
# History expansions will be verified before execution.
shopt -s histverify
# Save multi-line commands as one command
shopt -s cmdhist

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Allow use of variables in the prompt
shopt -s promptvars
