#!/usr/bin/env bash

# bash_paths

# Directories to be prepended to PATH
declare -a dirs_to_prepend=(
	"/usr/local/bin" # Ensure that this bin always takes precedence over `/usr/bin`
	"/usr/local/sbin"
	"$HOME/.linuxbrew/bin" # Add .linuxbrew support 
)

# Directories to be appended to PATH
declare -a dirs_to_append=(
	"/usr/bin"
	"$HOME/bin"
	"$HOME/.rvm/bin"
	"$(brew --prefix coreutils)/libexec/gnubin" # Add brew-installed GNU core utilities bin
	"$(brew --prefix homebrew/php/php55)/bin" # Add brew-installed php5 bin
	"$(brew --prefix npm)/bin" # Add npm-installed package bin
)

# Prepend directories to PATH
for index in ${!dirs_to_prepend[*]}
do
	if [ -d "${dirs_to_prepend[$index]}" ]; then
		# If these directories exist, then prepend them to existing PATH
		PATH="${dirs_to_prepend[$index]}:$PATH"
	fi
done

# Append directories to PATH
for index in ${!dirs_to_append[*]}
do
	if [ -d "${dirs_to_append[$index]}" ]; then
		# If these bins exist, then append them to existing PATH
		PATH="$PATH:${dirs_to_append[$index]}"
	fi
done

unset dirs_to_prepend dirs_to_append

export PATH
