#!/usr/bin/env bash

# bash_profile

# set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
	export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
	export TERM=xterm-256color
fi

# Up-front dotfiles configuration
# Not part of `load_dotfiles` because it must be sourced before anything else
# to be sure that commands like `brew` (when installed in a custom location)
# are already added to the PATH.
test -r "$HOME/.dotfilesrc" && source "$HOME/.dotfilesrc"

# Add for Linuxbrew
test -d "/home/linuxbrew/.linuxbrew" && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

load_dotfiles() {
	declare -a files=(
		$(dotfiles --prefix)/conf/bash/options # Options
		$(dotfiles --prefix)/conf/bash/exports # Exports
		$(dotfiles --prefix)/conf/bash/aliases # Aliases
		$(dotfiles --prefix)/conf/bash/functions # Functions
		$(dotfiles --prefix)/conf/bash/prompt # Custom bash prompt
		$(dotfiles --prefix)/conf/bash/paths # Path modifications
		$(dotfiles --prefix)/conf/bash/completions # Custom bash completion
		$(brew --prefix)/etc/bash_completion # Bash completion (installed via Homebrew)
		$HOME/.fzf.bash # fzf
		$HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
	)

	# if these files are readable, source them
	for index in ${!files[*]}
	do
		if [[ -r ${files[$index]} ]]; then
			source ${files[$index]}
		fi
	done
}

load_dotfiles
unset load_dotfiles

## DIRCOLORS
eval "$(dircolors -b ~/.dircolors)"

# list out tmux sessions on startup, don't show error if none
# https://twitter.com/climagic/status/567658485517930497
tmux list-sessions 2> /dev/null
