#!/usr/bin/env bash

# bash_profile

# set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
	export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
	export TERM=xterm-256color
fi

# Up-front dotfiles configuration
# Not part of `load_dotfiles` because it must be sourced before anything else
# to be sure that commands like `brew` (when installed in a custom location)
# are already added to the PATH.
# the following line/file doesn't appear to be present
test -r "$HOME/.dotfilesrc" && source "$HOME/.dotfilesrc"
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

load_dotfiles() {
	declare -a files=(
		#$HOME/.rvm/scripts/rvm # Load RVM into a shell session *as a function*
		$HOME/.dotfiles/conf/bash/options # Options
		$HOME/.dotfiles/conf/bash/exports # Exports
		$HOME/.dotfiles/conf/bash/aliases # Aliases
		$HOME/.dotfiles/conf/bash/functions # Options
		$HOME/.dotfiles/conf/bash/prompt # Custom bash prompt
		$HOME/.dotfiles/conf/bash/paths # Path modifications
		$HOME/.dotfiles/conf/bash/completions # Custom bash completion
		$(brew --prefix)/etc/bash_completion # Bash completion (installed via Homebrew)
		$(brew --prefix nvm)/nvm.sh # nvm 
		$HOME/.fzf.bash # fzf
		$HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
	)

	# if these files are readable, source them
	for index in ${!files[*]}
	do
		if [[ -r ${files[$index]} ]]; then
			source ${files[$index]}
		fi
	done
}

load_dotfiles
unset load_dotfiles

# list out tmux sessions on startup, don't show error if none
# https://twitter.com/climagic/status/567658485517930497
tmux list-sessions 2> /dev/null
