#!/usr/bin/env bash

source "./logger"

print_success "foo was called"
print_warning "foo was called"
#print_error "foo was called"
print_process "foo was called"
print_question "foo was called"

source "./utils"

is_required bar "npm is required to install packages" https://www.npmjs.org
