#!/usr/bin/env bash

# bash_profile

# set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
	export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
	export TERM=xterm-256color
fi

# Add for Linuxbrew
test -d "/home/linuxbrew/.linuxbrew" && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Add for Homebrew
test -d "/opt/homebrew" && eval "$(/opt/homebrew/bin/brew shellenv)"

load_dotfiles() {
	declare -a files=(
		"$HOME/.config/bash/options"           # Options
		"$HOME/.config/bash/exports"           # Exports
		"$HOME/.config/bash/aliases"           # Aliases
		"$HOME/.config/bash/functions"         # Functions
		"$HOME/.config/bash/prompt"            # Custom bash prompt
		"$HOME/.config/bash/paths"             # Path modifications
		"$HOME/.config/bash/completions"       # Custom bash completion

		"$HOME/.dircolors"                               # Custom dircolors/LS_COLORS
		"$(brew --prefix)/etc/bash_completion"           # Bash completion (installed via Homebrew)
		"$HOME/.fzf.bash"                                # fzf
		"$(brew --prefix)/share/forgit/forgit.plugin.sh" # forgit
		"$HOME/.bash_profile.local"                      # Local and private settings not under version control (e.g. git credentials)
	)

	# if these files are readable, source them
	for index in ${!files[*]}; do
		if [[ -r ${files[$index]} ]]; then
			source ${files[$index]}
		fi
	done
}

load_dotfiles
unset load_dotfiles

# list out tmux sessions on startup, don't show error if none
# https://twitter.com/climagic/status/567658485517930497
tmux list-sessions 2>/dev/null
