#!/usr/bin/env bash

# Allow aliases to be with sudo
alias sudo="sudo "

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."

# Always use color output for `ls`
if [[ "$(uname)" == "Darwin" ]]; then
	alias ls="ls -lAFGHhoST"
else
	alias ls="ls -aAHhloS --color"
	# export LS_COLORS="no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:"
fi

# Directory listing
if type -P 'tree' &> /dev/null; then
	alias ll="tree --dirsfirst -aLpughDFiC 1"
	alias lsd="ll -d"
else
	alias ll="ls -al"
	alias lsd='CLICOLOR_FORCE=1 ll | grep --color=never "^d"'
fi

# Concatenate and print content of files (add line numbers)
if type -P 'bat' &> /dev/null; then
	alias cat="bat"
fi

# Copy my public key to the pasteboard
if [[ "$(uname)" == "Darwin" ]]; then
	alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\\n'"
fi

# Runs `git pull` on every directory within the current directory
# `find .` search the current directory
# `-type d` find only directories, not files
# `-print` print the directory name
# `-maxdepth 1` limit the depth to one sub-directory
# `-execdir {} \;` run a custom command for every directory found
# `git --git-dir={}/.git --work-tree=$PWD/{} pull` git-pull each directory
#alias pullall="find . -type d -print -maxdepth 1 -execdir git --git-dir={}/.git --work-tree=$PWD/{} pull \"

# Disk Usage
# `du` means disk usage
# `-h` print out human readable
# `-d` depth (like layers deep); 1 means one layer of depth
alias disk="du -hd 1"

# Directory Size
# `du` means disk usage
# `-h` print out human readable
alias dirsize="du -sh"

# File size
# `-c/--format` the format to show;
# `%z` the format of total size, in bytes
alias filesize="stat -c '%z bytes'"

# Make grep more user friendly by highlighting matches
# # and exclude grepping through .git folders.
alias grep="grep --color=auto --exclude-dir=\\.git"

# curl a blank HTML file into Vim; open stdin in Vim by using the - flag
alias html="curl -L https://git.io/JTQI3 | vim -"

# Pass in a process to find, greps the running processes
alias process="ps aux | grep"

if type -P 'tmux' &> /dev/null; then
	alias tmux="tmux -2"
fi

# Aliasing eachdir like this allows you to use aliases/functions as commands.
alias eachdir=". eachdir"

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# Since changes to Bash configuration require a reload to the config file to
# become effective, save some typing by setting up an alias
alias refresh="source ~/.bashrc"

alias spoof="sudo ifconfig en0 ether fa:ke:ma:c"
# alias freewifi='sudo ifconfig en0 ether "$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//')"'

# Hit the Code directory from anywhere
alias code='cd ${CODE_DIRECTORY}'

# Play Star Wars as ASCII art
alias starwars="telnet towel.blinkenlights.nl"

# -I prompt once before removing more than three files, or when removing
# recursively. Less intrusive than -i, while still giving protection against
# most mistakes. (depends on brew coreutils)
# https://github.com/sindresorhus/guides/blob/master/how-not-to-rm-yourself.md
if brew list "coreutils" &> /dev/null; then
	alias rm="rm -I"
else
	alias rm="rm -i"
fi

# > An additional neat feature of FZF is that it can show a preview window to
# > display the results of a command. For example, we can use `fzf` with `bat`
# > to pretty-print the contents of a file, like in the command below. Bat is
# > an alternative to `cat` that supports syntax highlighting. The {-1} stands
# > for the selected file.
# https://medium.com/@GroundControl/better-git-diffs-with-fzf-89083739a9cb
if brew list "fzf" &> /dev/null && brew list "bat" &> /dev/null; then
	alias fzf="fzf --preview 'bat {-1} --color=always'"
fi

# Update vim plugins from anywhere
alias vu="vim +PluginInstall +qall"

# reinstall deps
alias npmplease="rm -rf node_modules/ && rm -f package-lock.json && npm install"
