.\" Process this file with
.\" groff -man -Tascii cdl.1
.\"
.TH "DOTFILES" 1 "JANUARY 2014" Unix "User Manuals"
.SH NAME
\fBdotfiles\fR \- Installs all necessary configuration files for development
.SH SYNOPSIS
\fBdotfiles\fR \-\-version
.br
.\fBdotfiles\fR [options]
.SH DESCRIPTION
Installs and/or updates all files necessary to configure a development machine including bash, git, runcom, ssh, & vim cconfiguration.
.SH OPTIONS
.IP "\fb-e, --edit\fR"
Edit the dotfiles
.IP "\fb--prefix\fR"
.RI "Display dotfiles install path. " "Default: \fb/usr/local/opt\fR"
.IP "\fb-t, --test\fR"
Run the roundup test suite.
.IP "\fb-v, --version\fR"
Print the currently installed version.
.SH RETURN VALUES
The following exit codes are possible:
.IP "\fb0\fR" 
success
.IP "\fb1\fR" 
general error, typically a bad flag or value
.IP "\fb2\fR" 
missing dependency error
.SH REPORTING BUGS
.RI "Report bugs to the Github repository <" "https://github.com/chrisopedia/dotfiles/issues" ">"
.SH AUTHOR
.RI "Newton <" "https://twitter.com/chrisOHpedia" ">"
