#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$DOTFILES_DIRECTORY/lib/logger"

# @public
# @requires logger (local)
# @requires brew
# @param $file - path to file where homebrew formulae are listed out
install_formulae() {
	local file=$1

	is_required brew "Homebrew is required to install formulae" https://brew.sh \

	print_process "Installing and updating Homebrew formulae"

	# Updating Homebrew
	print_process "Updating Homebrew"
	brew update

	# Upgrade Homebrew formulaes
	print_process "Upgrading any existing formulae"
	brew upgrade

	# Install Homebrew formulae (macOS way only now?; 2020/11/05)
	print_process "Installing all formulae"
	brew bundle --file="$file"

	print_process "Cleaning up Homebrew"
	brew cleanup

	[[ $? ]] \
		&& print_success "Homebrew has been updated, all formulae have been upgraded, and all new formulae have been installed"
}
