#!/usr/bin/env bash

# location of log file
export LOG="/tmp/$GITHUB_REPO.log"
# readonly TODAY=$(date +"%m-%d-%y")

# Success logging
print_success() {
	local message=$1

	echo "$(date) SUCCESS: $message" >> "$LOG"
	printf "%s✓ Success:%s\\n" "$(tput setaf 2)" "$(tput sgr0) $message"
}

# Warning logging
print_warning() {
	local message=$1

	echo "$(date) WARNING: $message" >> "$LOG"
	printf "%s ⚠Warning:%s!\\n" "$(tput setaf 3)" "$(tput sgr0) $message"
}

# Informational logging
print_info() {
	local message=$1

	echo "$(date) INFO: $message" >> "$LOG"
	printf "%s Info:%s\\n" "$(tput setaf 6)" "$(tput sgr0) $message"
}

# Error logging
print_error() {
	local message=$1

	echo "$(date) ERROR: $message" >> "$LOG"
	printf "%s⊘ Error:%s %s. Aborting!\\n" "$(tput setaf 1)" "$(tput sgr0)" "$message"
}

# Command/Processing logging
print_process() {
	local message=$1

	echo "$(date) PROCESSING: $message" >> "$LOG"
	printf "%s┃%s %s...\\n" "$(tput setaf 6)" "$(tput sgr0)$(tput setaf 7)" "$message$(tput sgr0)"
}

# Question logging
print_question() {
	local message=$1

	echo "$(date) QUESTION:  $message" >> "$LOG"
	printf "\\n%s===> %s?%s " "$(tput setaf 3)" "$message" "$(tput sgr0)"
}
