#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$DOTFILES_DIRECTORY/lib/logger"

# Checks if whats passed in is empty, specifically if the string is actually passed in
is_empty() {
	local var=$1

	[[ -z $var ]]
}

# Checks if whats passed in is not empty, specifically if the string is actually passed in
is_not_empty() {
	local var=$1

	[[ -n $var ]]
}

# Checks if whats passed in is a file and exists
file_exists() {
	local var=$1

	[[ -e $var ]]
}

# Checks if whats passed in is a file, exists, and is a regular file
is_a_file() {
	local file=$1

	[[ -f $file ]]
}

# Checks if whats passed in is a directory
is_a_directory() {
	local dir=$1

	[[ -d $dir ]]
}

# Check to ensure a program exists before relying on it
is_required() {
	local program=$1
	local message=$2
	local url=$3

	type -P "$program" >/dev/null || {
		print_error "$message"
		echo "Download it at $url"
		exit 2
	}
}

# @private
# @param $program - a function or program to process each item
# @param $file - path to a file with each item separated on a line
bulk_install() {
	local program=$1
	local file=$2

	while IFS="" read -r p || [ -n "$p" ]
	do
		#printf '%s\n' "$p"
		$program "$p"
	done < "$file"
}

# program functions
error_out() {
	local message=$1

	print_error "$message"
	printf "Run the installer <%shttps://github.com/iamnewton/dotfiles#how-to-install%s>\\n" "$(tput smul)" "$(tput rmul)"
	exit 1
}
