#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$DOTFILES_DIRECTORY/lib/logger"
# shellcheck source=/dev/null
source "$DOTFILES_DIRECTORY/lib/utils"

# @private
# @require logger
_sync_vim() {
	print_process "Synchronizing .vim directory and symlinking runcom (.vimrc) file"
	rsync -avz --quiet "$DOTFILES_DIRECTORY/conf/vim"  "$HOME/.vim"
	ln -sfn "$DOTFILES_DIRECTORY/conf/runcom/vim"      "$HOME/.vimrc"

	[[ $? ]] \
		&& print_success "Synchronized .vim directory and symlinked runcom (.vimrc) file"
}

# @private
# @require logger
_update_vim_plugins() {
	print_process "Installing ViM plugins"
	vim "$HOME/.vim/settings/bundles.vim" +PluginInstall +PluginUpdate +qall

	[[ $? ]] \
		&& print_success "Installed ViM plugins"
}

# @public
# @require logger
# @require utils
setup_vim() {
	print_process "Setting up ViM"
	print_process "Removing .vim directory, if it exists"
	file_exists "$HOME/.vim" \
		&& rm -rf "$HOME/.vim" \
		&& _sync_vim

	is_a_file "$HOME/.vim/settings/bundles.vim" \
		&& _update_vim_plugins

	[[ $? ]] \
		&& print_success "ViM setup successfully"
}
