#!/usr/bin/env bash
#
# common <tab> completions

# Brew completion
if [[ -r "/home/linuxbrew/.linuxbrew/etc/profile.d/bash_completion.sh" ]]; then
	source "/home/linuxbrew/.linuxbrew/etc/profile.d/bash_completion.sh"
fi

# Enable bash <tab> completion for fx
if brew list "fx" &>/dev/null; then
	source <(fx-completion --bash)
fi

if brew list "fzf" &>/dev/null; then
	source <(fzf --bash)
fi

# Enable bash <tab> completion for fzf
if brew list "fzf" &>/dev/null; then
	source "$(brew --prefix)/opt/fzf/shell/completion.bash"
	source "$(brew --prefix)/opt/fzf/shell/key-bindings.bash"
fi

# Enable bash <tab> completion for z
if brew list "z" &>/dev/null; then
	source "$(brew --prefix)/etc/profile.d/z.sh"
fi

# SSH auto-completion based on entries in known_hosts.
if [[ -e "$HOME/.ssh/known_hosts" ]]; then
	complete -o default -W "$(cat "$HOME/.ssh/known_hosts" | sed 's/[, ].*//' | sort | uniq | grep -v '[0-9]')" ssh scp sftp
fi
