#!/usr/bin/env bash

# Custom configuration for ACK
export ACKRC="$HOME/.config/ackrc"

# Custom configuration for CURL
export CURL_HOME="$HOME/.config/curlrc"

# Make vim the default editor
export EDITOR="vim"

# Make vim the default editor for git
export GIT_EDITOR="vim"

# Custom configuration for Gitmoji Fuzzy Hook
export GITMOJI_FUZZY_HOOK_ROOT="$HOME/.local/bin/gitmoji-fuzzy-hook-init"

# @TODO: automate this folder creation in dotfiles install
export GOPATH="$(brew --prefix)/lib/go"

# Custom configuration for GPG
export GNUPGHOME="$HOME/.config/gnupg"

# Always enable colored `grep` output
# Noted in terminal that this option is deprecated
# export GREP_OPTIONS="--color=auto"

# Entries beginning with space aren't added into history, and duplicate
# entries will be erased (leaving the most recent entry).
export HISTCONTROL=ignorespace:erasedups

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE=100000

# Make some commands not show up in history
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=500000

# Set the format for the history file
export HISTTIMEFORMAT="%h/%d/%y-%H:%M:%S "

# Custom configuration for Input
export INPUTRC="$HOME/.config/readline/inputrc"

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Linuxbrew library path
export LD_LIBRARY_PATH="$(brew --prefix)/lib"

# Highlight section titles in manual pages
export LESS_TERMCAP_md="$ORANGE"
export LESSKEY="$HOME/.config/lesskey"

# Add colors format to the LS command output
export CLICOLOR=1

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# NVM directory (choosing n over nvm)
# export NVM_DIR=$HOME/.nvm

# N (node version manager) directory
export N_PREFIX="$HOME/.n"

# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# ripgrep configuration path
export RIPGREP_CONFIG_PATH="$HOME/.config/ripgreprc"

# wget configuration path
export WGETRC="$HOME/.config/wgetrc"

# GPG Signage
GPG_TTY=$(tty)
export GPG_TTY

# Enable terraform logging to Standard Output (stdout)
export TF_LOG=1

