#!/usr/bin/env bash

# bash_paths

# Directories to be prepended to PATH (highest priority → lowest)
declare -a dirs_to_prepend=(
	"$HOME/.local/n/bin" # Node managed by `n`
	"$HOME/bin"          # Personal scripts
	"$HOME/.local/bin"   # Personal local bin installs (pip, etc.)
	"/usr/local/bin"     # Common local installs (sometimes non-Brew)
	"/usr/local/sbin"
	"/opt/homebrew/bin" # Homebrew userland
	"/opt/homebrew/sbin"
	"/opt/whalebrew/bin" # Other custom tools
)

# Directories to be appended to PATH (lowest priority, fallback only)
declare -a dirs_to_append=(
	"/usr/bin" # System binaries
	"/bin"
	"/usr/sbin"
	"/sbin"
	"$(brew --prefix coreutils)/libexec/gnubin" # GNU utils from Brew
	"$(brew --prefix npm)/bin"                  # npm global installs (Brew-managed)
	"$FORGIT_INSTALL_DIR/bin"
)

# Prepend directories to PATH
for index in ${!dirs_to_prepend[*]}; do
	if [ -d "${dirs_to_prepend[$index]}" ]; then
		# If these directories exist, then prepend them to existing PATH
		PATH="${dirs_to_prepend[$index]}:$PATH"
	fi
done

# Append directories to PATH
for index in ${!dirs_to_append[*]}; do
	if [ -d "${dirs_to_append[$index]}" ]; then
		# If these bins exist, then append them to existing PATH
		PATH="$PATH:${dirs_to_append[$index]}"
	fi
done

unset dirs_to_prepend dirs_to_append

export PATH
